import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0C2039',
    marginBottom: 8,
    fontFamily: 'Helvetica',
  },
  subtitle: {
    fontSize: 16,
    color: '#0C2039',
    marginBottom: 24,
    fontFamily: 'Avenir',
  },
  serviceCards: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 10,
  },
  card: {
    flex: 1,
    height: 154,
    borderRadius: 12,
    paddingTop: 49,
    paddingHorizontal: 10,
    position: 'relative',
  },
  selectedCard: {
    backgroundColor: '#00763E',
  },
  unselectedCard: {
    backgroundColor: '#f5f5f5',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    color: '#000',
    fontFamily: 'Helvetica',
  },
  cardDescription: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
    fontFamily: 'Avenir',
    fontWeight: '500',
  },
  selectedText: {
    color: '#fff',
  },
  radioOuter: {
    position: 'absolute',
    top: 16,
    left: 10,
    width: 20,
    height: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ccc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  radioSelected: {
    backgroundColor: '#fff',
  },
  formSection: {
    gap: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 0,
    color: '#0C2039',
    fontFamily: 'Avenir',
  },
  selectBox: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
  },
  inputGroup: {
    marginTop: 0,
  },
  dateSection: {
    marginTop: 20,
  },
  dateOptions: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 10,
    marginBottom: 20,
  },
  dateOption: {
    flex: 1,
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
  },
  //   dateOptionContent: {
  //     flexDirection: 'row',
  //     alignItems: 'center',
  //     justifyContent: 'center',
  //   },
  dateOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start', // Changed to flex-start to align items to the left
    gap: 8, // Add gap between checkmark and text
  },
  selectedDateOption: {
    backgroundColor: '#f5f5f5',
  },
  //   checkmark: {
  //     marginRight: 8,
  //     width: 18,
  //     height: 18,
  //     borderRadius: 3,
  //     backgroundColor: '#00763E',
  //     justifyContent: 'center',
  //     alignItems: 'center',
  //   },
  //   checkmarkSelected: {},
  checkmark: {
    width: 20,
    height: 20,
    borderRadius: 2,
    backgroundColor: '#00763E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkUnselected: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#C7C7C7',
  },
  checkmarkText: {
    color: '#fff',
    fontSize: 14,
  },
  dateOptionText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Avenir',
  },
  selectedDateOptionText: {
    color: '#000',
  },
  dateInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  dateInputSelected: {
    borderColor: '#00763E',
    borderWidth: 1,
  },
  dateInputText: {
    fontSize: 16,
    color: '#666',
  },
  timeOfDayOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 16,
  },
  timeOfDaySelected: {
    backgroundColor: '#fff',
  },
  checkBox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    // backgroundColor: '#C7C7C7',
    borderColor: '#C7C7C7',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkBoxSelected: {
    backgroundColor: '#00763E',
    borderColor: '#00763E',
  },
  checkBoxText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  timeOfDayText: {
    fontSize: 14,
    color: '#000',
    fontFamily: 'Avenir',
  },
  timeSlots: {
    gap: 10,
  },
  timeSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    gap: 16,
  },
  selectedTimeSlot: {
    backgroundColor: '#00763E',
  },
  timeSlotIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  selectedTimeSlotIcon: {
    backgroundColor: '#fff',
  },
  timeSlotContent: {
    flex: 1,
  },
  timeSlotTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
    color: '#0C2039',
    fontFamily: 'Helvetica',
  },
  timeSlotRange: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'Avenir',
  },
  timeSlotRangeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timeSlotRangeLabel: {
    fontSize: 12,
    color: '#0C2039',
    fontFamily: 'Avenir',
    fontWeight: '500',
  },
  timeSlotRangeValue: {
    fontSize: 12,
    color: '#0C2039',
    fontFamily: 'Avenir',
    fontWeight: '800',
  },
  selectedTimeSlotText: {
    color: '#fff',
  },
  timeSlotImage: {
    width: 24,
    height: 24,
    tintColor: '#292D32',
  },
  selectedTimeSlotImage: {
    tintColor: '#00763E',
  },
  timeSlotRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#DBDBDB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeSlotRadioSelected: {
    backgroundColor: '#00763E',
    borderColor: '#fff',
  },
  timeSlotRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
  },
  continueButton: {
    backgroundColor: '#00763E',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 32,
  },
  continueButtonDisabled: {
    // backgroundColor: '#E0E0E0',
    backgroundColor: '#00763E80',
    opacity: 0.7,
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Helvetica',
  },
  iosDatePicker: {
    width: '100%',
    backgroundColor: 'white',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    marginBottom: 16,
  },
  buttonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Helvetica',
    marginLeft: 8,
  },
  input: {
    height: 50,
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#000',
  },
  inputError: {
    borderColor: '#ff4444',
    borderWidth: 1,
  },
  errorText: {
    color: '#ff4444',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
  },
  fadeIn: {
    opacity: 1,
    transform: [{translateY: 0}],
  },
  inputContainer: {
    marginTop: 0,
    opacity: 0,
    transform: [{translateY: 10}],
    animation: 'fadeIn 0.3s ease-in-out forwards',
  },
});
